### PR TITLE
Test pull request

### PR DESCRIPTION
**Pull request by mxm**

### CODE REVIEW

**Comment by flinkqa** [comment]
Tested pull request.Result: 
allexport       off
braceexpand     on
emacs           off
errexit         on
errtrace        off
functrace       off
hashall         on
histexpand      off
history         off
ignoreeof       off
interactive-comments    on
keyword         off
monitor         off
noclobber       off
noexec          off
noglob          off
nolog           off
notify          off
nounset         off
onecmd          off
physical        off
pipefail        off
posix           off
privileged      off
verbose         off
vi              off
xtrace          off
Cloning into 'flink'...
Already on 'master'
From http://git-wip-us.apache.org/repos/asf/flink
- branch            master     -> FETCH_HEAD
  Already up-to-date.
  Running ./tools/qa-check.sh
  _qa_workdir doesnt exist. Creating it
  There is no flink copy in the workdir. Cloning flink
  ./tools/qa-check.sh: line 55: git: command not found
  ./tools/qa-check.sh: line 58: cd: flink: No such file or directory
  ./tools/qa-check.sh: line 60: git: command not found
  ./tools/qa-check.sh: line 61: git: command not found
  ./tools/qa-check.sh: line 67: cd: flink: No such file or directory
  Computing Flink QA-Check results (please be patient).
  ./tools/qa-check.sh: line 90: mvn: command not found
  ./tools/qa-check.sh: line 109: mvn: command not found
  ./tools/qa-check.sh: line 131: mvn: command not found
  ./tools/qa-check.sh: line 96: mvn: command not found
  :+1: The number of javadoc errors was 0 and is now 0
  ./tools/qa-check.sh: line 114: mvn: command not found
  :+1: The number of compiler warnings was 0 and is now 0
  ./tools/qa-check.sh: line 137: mvn: command not found
  :+1: The number of files in the lib/ folder was 0 before the change and is now 0
  :-1: The change contains @author tags
  QA-Check finished.
  Overall result: :-1:. Some tests failed. Please check messages above

**Comment by mxm** [comment]
run qa

**Comment by flinkqa** [comment]
Tested pull request but QA script returned errors.Result: 
Running ./tools/qa-check.sh
run.sh: line 56: 23264 Killed                  timeout -s SIGKILL 2h docker run -v `pwd`:/mnt/ qa-bot bash -c "cd /mnt/ && ./tools/qa-check.sh" &>/dev/null
Running the QA-Check failed.
dd7e9b86ff47
dd7e9b86ff47

**Comment by mxm** [comment]
run qa

**Comment by flinkqa** [comment]
Tested pull request.Result: 
Running ./tools/qa-check.sh

real    192m36.002s
user    0m0.112s
sys 0m0.000s
Computing Flink QA-Check results (please be patient).
:+1: The number of javadoc errors was 185 and is now 179
:+1: The number of compiler warnings was 660 and is now 659
:+1: The number of files in the lib/ folder was 2 before the change and is now 2
:-1: The change contains @author tags
QA-Check finished.
Overall result: :-1:. Some tests failed. Please check messages above
997e1a821a55
997e1a821a55

**Pull request closed without merging**
